### PR TITLE
HKTMXTiledMap

### PR DESCRIPTION
**Pull request by skyhawk2891**
Includes everything (plus a few fix from http://www.cocos2d-iphone.org/forum/topic/17945 )

github is a boggle to use o_O

Hoping this works? o_O

### CODE REVIEW

**Comment by psineur** [comment]
Very good, thank you!

But there's some issues that must be solved, before merging this.
1. Most important - we can't use blocks, cause they aren't supported in iOS 3. So you need to rewrite it without using blocks and check for some other unsupported features/ dependencies.
2. Copyrights should be added to all files, i see that in your files there's no copyrights and license, and in others - there's copypaste from others files. Don't hesitate to add your name, link to blog, etc. Add MIT License to all your files - and that's all.
3. You forked extensions repo and created a new branch perfectly. The only issue - that in pull request you also need to target develop branch - this will make pull request look better.
4. Better README needed: links to editor(Tiled), some additional text about how it works, and most important: all info that you have about issues.

So here's the plan: work on your branch, fix blocks & copyrights, edit README and close this pull request and create new (but this time set develop branch as target, it will look like 

```
skyhawk2891 wants someone to merge 3 commits into cocos2d:develop from skyhawk2891:HKTMXTiledMap
```

When you will close this pull request - please provide a link to new one in comments.

Thanks!

**Comment by skyhawk2891** [comment]
https://github.com/cocos2d/cocos2d-iphone-extensions/pull/34

**Comment by psykano** [comment]
I have some free time to look into this, is there any place I can get the most recent source?

Edit: Nevermind, I found it.

**Comment by psineur** [comment]
Same code, i still haven't merged it.
Will do this right after creating release-0.1.2 branch.

13.07.11 22:05, psykano пишет:

> I have some free time to look into this, is there any place I can get the most recent source?

**Pull request closed without merging**
