### PR TITLE
cocos2d v2.0 support for cocos2d-extensions

### PR DESCRIPTION
**Pull request by ricardoquesada**
Hi,

This is the initial cocos2d v2.0 support for cocos2d-iphones.

All iOS tests are working.

Todo: Make the Mac tests work.

### CODE REVIEW

**Comment by ricardoquesada** [comment]
I think the "pull request" was not clean... ouch.

Apparently I sent the pull request against "master" and not "develop"

This is the only important commit:
https://github.com/ricardoquesada/cocos2d-iphone-extensions/commit/1c3d54a47c7b302c0f5eb10552d7589362df18c3

**Comment by ricardoquesada** [comment]
2 more commits:
Added mac support and fixed File Downlaoded progress test

**Comment by psineur** [comment]
Ok, i just started trying to support this for main branch here: https://github.com/cocos2d/cocos2d-iphone-extensions/tree/feature-cocos2d_2.0-support

I will mention #99 from all commits in that branch - so pull request feed should be updated.

Issue with progress: #100

@ricardoquesada What was changed in the mac xib file? Diff's of xib is always messy - hard to understand.

**Comment by ricardoquesada** [comment]
@psineur I renamed MacGLView to CCGLView.

**Comment by psineur** [comment]
Merged 'feature-cocos2d_2.0-support' into develop in 60ae22d5c1769cc2d0b20e7643cc15c13250c879

**Pull request closed without merging**
